### ISSUE TITLE
error starting

### ISSUE THREAD

**Issue by teehehe** [mrzeappleGit/PalWorld-Control-Center#1]
got an error it couldn't find palserver.exce but then right after that the message said server started successfully (server wasnt started)
mainly just reporting it says successful even tho its not since its a directory issue on my side

![image](https://github.com/mrzeappleGit/PalWorld-Control-Center/assets/49544376/8d2e4089-448c-48a2-a925-cf2775006a85)

![image](https://github.com/mrzeappleGit/PalWorld-Control-Center/assets/49544376/85d40175-52cd-443a-bc42-ee7d51b9e99b)

**Comment by mrzeappleGit** [comment]
Thank you for bringing this to my attention, I have updated it so if the application doesn't start the success message doesn't appear.
