### ISSUE TITLE
not running bat file correctly

### ISSUE THREAD

**Issue by teehehe** [mrzeappleGit/PalWorld-Control-Center#2]
not sure if its just the way my stuff was installed and setup but it wouldn't run the bat file correctly. It would say couldnt find the file steamcd.exe (it is in the same folder where the bat file is created) I had to specify the working directory in the sub process command. I am no python guy so i wasn't sure how to use an variable for the location so i just hardcoded my location. 

def run_bat_file(file_path, app_name):
    try:
        subprocess.run(file_path, shell=True)

to 

def run_bat_file(file_path):
    try:
        subprocess.run(file_path, shell=True, cwd="C:\Program Files (x86)\Steam\steamcmd")

**Comment by mrzeappleGit** [comment]
I have updated that, since my steamcmd is "C:\steamcmd" I have tied the cwd to the one selected. I added a button to change the folder.
