### ISSUE TITLE
cant set folder server

### ISSUE THREAD

**Issue by mazixs** [mrzeappleGit/PalWorld-Control-Center#3]
Im install server with tool windowsgsm. 
If I specify the path to the server files, the program does not see anything, because it is not the path to steam cmd
I think the path to the server files should be sufficient for the program to work?

**Comment by mrzeappleGit** [comment]
Just to clarify, did you install the palworld server via windowsgsm but now want to use my tool instead of windowsgsm?

**Comment by mazixs** [comment]
the problem with windows gsm is the lack of management tools. That is, there are no RCON functions.

**Comment by mrzeappleGit** [comment]
I have made an update where you should now be able to select the steamcmd folder and the palserver folder
